name: Helper - Terraform plan

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      plan-artifact-name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  plan:
    environment: ${{ inputs.environment }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          terraform plan -no-color -out=tfplan >> $GITHUB_STEP_SUMMARY
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Save plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.plan-artifact-name }}
          path: ${{ inputs.working-directory }}
