name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "upload"
          app_location: "/" # Location of your application code (e.g., "/", "app")
          output_location: "build" # Folder where your build output is generated (e.g., "build", "dist")
          api_location: "api" # Optional: if you have an Azure Functions backend

