name: Helper - build and deploy UI environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN:
        required: true

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Build and Deploy

    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/frontend/angular"
          output_location: "dist/angular"
          app_build_command: "npm run build -- --configuration ${{ inputs.environment }}"
