name: Release to DEV

on:
  workflow_dispatch:

jobs:

  release:    
    uses: ./.github/workflows/build-deploy-environment.yml
    with:
      environment: development
    secrets: 
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }} 