name: Release API - DEV

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/build-deploy-backend-environment.yml
    with:
      environment: development
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
